language: go

go:
  - 1.8
  - 1.9
  - 1.10

install:
  - go get gopkg.in/alecthomas/kingpin.v2
  - go get github.com/alecthomas/template
  - go get github.com/alecthomas/units
  - go get github.com/fatih/color

script:
  - go test -v -p 1 ./logger ./commands ./utils ./
  - go build -o playwright main.go
